<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mscc.GenerativeAI" Version="2.8.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductReviewAnalysis.Common\ProductReviewAnalysis.Common.csproj" />
  </ItemGroup>

</Project>
